
# DAIOE SSYK2012 Workflow

Organized end-to-end flow for preparing DAIOE + SCB SSYK data.

## 1) Setup Paths and Source URLs

Define local paths and the remote parquet sources used in this notebook.

In [15]:
import polars as pl
from pathlib import Path
from fcts import inspect_lazy

root = Path.cwd().resolve()
data_dir = root/ "data"
data_dir.mkdir(parents=True, exist_ok=True)

daioe_source: str = (
    "https://raw.githubusercontent.com/joseph-data/AI_Econ_daioe_years/development/"
    "data/daioe_scb_years_all_levels.parquet"
)

scb_source: str = (
        "https://raw.githubusercontent.com/joseph-data/AI_Econ_daioe_months/daioe_pull/"
        "data/scb_months.parquet"

)

In [16]:
daioe_lf = pl.scan_parquet(
    daioe_source
)

scb_lf = pl.scan_parquet(
    scb_source
)

## 2) Obtain Raw DAIOE and SCB Tables

Load both inputs as Polars `LazyFrame`s so transformation steps stay lazy and memory-safe.

## 3) Quick Validation of Raw Inputs

Preview the first rows from each source before applying cleaning rules.

In [17]:
print(daioe_lf.head(5).collect())

shape: (5, 65)
┌───────┬───────────┬───────┬───────┬───┬──────────────┬──────────────┬──────────────┬─────────────┐
│ level ┆ ssyk_code ┆ age   ┆ sex   ┆ … ┆ daioe_lngmod ┆ daioe_transl ┆ daioe_speech ┆ daioe_genai │
│ ---   ┆ ---       ┆ ---   ┆ ---   ┆   ┆ _Level_Expos ┆ at_Level_Exp ┆ rec_Level_Ex ┆ _Level_Expo │
│ str   ┆ str       ┆ str   ┆ str   ┆   ┆ ure          ┆ osure        ┆ posure       ┆ sure        │
│       ┆           ┆       ┆       ┆   ┆ ---          ┆ ---          ┆ ---          ┆ ---         │
│       ┆           ┆       ┆       ┆   ┆ i8           ┆ i8           ┆ i8           ┆ i8          │
╞═══════╪═══════════╪═══════╪═══════╪═══╪══════════════╪══════════════╪══════════════╪═════════════╡
│ SSYK3 ┆ 531       ┆ 40-44 ┆ women ┆ … ┆ 3            ┆ 3            ┆ 3            ┆ 3           │
│ SSYK3 ┆ 933       ┆ 50-54 ┆ women ┆ … ┆ 2            ┆ 2            ┆ 2            ┆ 1           │
│ SSYK3 ┆ 141       ┆ 60-64 ┆ men   ┆ … ┆ 4            ┆ 4            ┆ 4            ┆ 4           │
│ SSYK3 ┆ 324       ┆ 45-49 ┆ men   ┆ … ┆ 2            ┆ 3            ┆ 2            ┆ 2           │
│ SSYK3 ┆ 422       ┆ 40-44 ┆ women ┆ … ┆ 5            ┆ 5            ┆ 5            ┆ 5           │
└───────┴───────────┴───────┴───────┴───┴──────────────┴──────────────┴──────────────┴─────────────┘

In [18]:
print(scb_lf.head(5).collect())

shape: (5, 5)
┌────────┬─────┬──────────┬───────┬────────────┐
│ code_1 ┆ sex ┆ month    ┆ value ┆ occupation │
│ ---    ┆ --- ┆ ---      ┆ ---   ┆ ---        │
│ str    ┆ str ┆ str      ┆ f64   ┆ str        │
╞════════╪═════╪══════════╪═══════╪════════════╡
│ 1      ┆ men ┆ 2015-Jan ┆ 169.8 ┆ Managers   │
│ 1      ┆ men ┆ 2015-Feb ┆ 164.8 ┆ Managers   │
│ 1      ┆ men ┆ 2015-Mar ┆ 156.2 ┆ Managers   │
│ 1      ┆ men ┆ 2015-Apr ┆ 171.5 ┆ Managers   │
│ 1      ┆ men ┆ 2015-May ┆ 177.8 ┆ Managers   │
└────────┴─────┴──────────┴───────┴────────────┘

## 4) Clean SCB Monthly Data

Remove military records and extract `year` from `month` for downstream joins.

In [19]:
scb_lf_clean = scb_lf\
    .filter(pl.col("code_1").str.starts_with(0).not_())\
        .with_columns(
    pl.col("month")
      .str.extract(r"^(\d{4})", 1)
      .cast(pl.Int64)
      .alias("year")
)


print(scb_lf_clean.limit(10).collect())

shape: (10, 6)
┌────────┬─────┬──────────┬───────┬────────────┬──────┐
│ code_1 ┆ sex ┆ month    ┆ value ┆ occupation ┆ year │
│ ---    ┆ --- ┆ ---      ┆ ---   ┆ ---        ┆ ---  │
│ str    ┆ str ┆ str      ┆ f64   ┆ str        ┆ i64  │
╞════════╪═════╪══════════╪═══════╪════════════╪══════╡
│ 1      ┆ men ┆ 2015-Jan ┆ 169.8 ┆ Managers   ┆ 2015 │
│ 1      ┆ men ┆ 2015-Feb ┆ 164.8 ┆ Managers   ┆ 2015 │
│ 1      ┆ men ┆ 2015-Mar ┆ 156.2 ┆ Managers   ┆ 2015 │
│ 1      ┆ men ┆ 2015-Apr ┆ 171.5 ┆ Managers   ┆ 2015 │
│ 1      ┆ men ┆ 2015-May ┆ 177.8 ┆ Managers   ┆ 2015 │
│ 1      ┆ men ┆ 2015-Jun ┆ 151.0 ┆ Managers   ┆ 2015 │
│ 1      ┆ men ┆ 2015-Jul ┆ 174.6 ┆ Managers   ┆ 2015 │
│ 1      ┆ men ┆ 2015-Aug ┆ 174.4 ┆ Managers   ┆ 2015 │
│ 1      ┆ men ┆ 2015-Sep ┆ 157.0 ┆ Managers   ┆ 2015 │
│ 1      ┆ men ┆ 2015-Oct ┆ 189.5 ┆ Managers   ┆ 2015 │
└────────┴─────┴──────────┴───────┴────────────┴──────┘

## 5) Prepare DAIOE Level-1 Aggregates

Filter DAIOE to SSYK level 1 and compute yearly weighted means for merge keys.

In [20]:
weighted_daioe = daioe_lf\
    .filter(
        (pl.col("level") == "SSYK1")
        )\
        .select(
            pl.col(["level", "ssyk_code", "year", "weight_sum"]),
            pl.col("^daioe_.*$"),
            pl.col("^pctl_daioe_.*$")
            )\
            .group_by(["level", "ssyk_code", "year"])\
                .agg([
                    pl.col("weight_sum").mean().cast(pl.Int64),
                    pl.col("^daioe_.*$").mean(),
                    pl.col("^pctl_daioe_.*$").mean()
                    ])

weighted_daioe.limit(10).collect()

shape: (10, 59)
┌───────┬───────────┬──────┬────────────┬───┬─────────────┬─────────────┬─────────────┬────────────┐
│ level ┆ ssyk_code ┆ year ┆ weight_sum ┆ … ┆ pctl_daioe_ ┆ pctl_daioe_ ┆ pctl_daioe_ ┆ pctl_daioe │
│ ---   ┆ ---       ┆ ---  ┆ ---        ┆   ┆ lngmod_wavg ┆ translat_wa ┆ speechrec_w ┆ _genai_wav │
│ str   ┆ str       ┆ i64  ┆ i64        ┆   ┆ ---         ┆ vg          ┆ avg         ┆ g          │
│       ┆           ┆      ┆            ┆   ┆ f64         ┆ ---         ┆ ---         ┆ ---        │
│       ┆           ┆      ┆            ┆   ┆             ┆ f64         ┆ f64         ┆ f64        │
╞═══════╪═══════════╪══════╪════════════╪═══╪═════════════╪═════════════╪═════════════╪════════════╡
│ SSYK1 ┆ 1         ┆ 2024 ┆ 356245     ┆ … ┆ 75.0        ┆ 75.0        ┆ 75.0        ┆ 75.0       │
│ SSYK1 ┆ 1         ┆ 2023 ┆ 333614     ┆ … ┆ 75.0        ┆ 75.0        ┆ 75.0        ┆ 75.0       │
│ SSYK1 ┆ 3         ┆ 2015 ┆ 553719     ┆ … ┆ 62.5        ┆ 62.5        ┆ 62.5        ┆ 62.5       │
│ SSYK1 ┆ 5         ┆ 2014 ┆ 890932     ┆ … ┆ 50.0        ┆ 50.0        ┆ 50.0        ┆ 50.0       │
│ SSYK1 ┆ 4         ┆ 2024 ┆ 392453     ┆ … ┆ 87.5        ┆ 100.0       ┆ 100.0       ┆ 87.5       │
│ SSYK1 ┆ 6         ┆ 2017 ┆ 34657      ┆ … ┆ 37.5        ┆ 37.5        ┆ 37.5        ┆ 12.5       │
│ SSYK1 ┆ 8         ┆ 2023 ┆ 341160     ┆ … ┆ 12.5        ┆ 25.0        ┆ 25.0        ┆ 12.5       │
│ SSYK1 ┆ 2         ┆ 2015 ┆ 973635     ┆ … ┆ 87.5        ┆ 87.5        ┆ 87.5        ┆ 100.0      │
│ SSYK1 ┆ 5         ┆ 2022 ┆ 1006464    ┆ … ┆ 50.0        ┆ 50.0        ┆ 50.0        ┆ 50.0       │
│ SSYK1 ┆ 9         ┆ 2015 ┆ 233350     ┆ … ┆ 0.0         ┆ 0.0         ┆ 12.5        ┆ 0.0        │
└───────┴───────────┴──────┴────────────┴───┴─────────────┴─────────────┴─────────────┴────────────┘

In [23]:
inspect_lazy(scb_lf_clean)

Rows: 2,394
Columns: 6

In [24]:
inspect_lazy(weighted_daioe)

Rows: 99
Columns: 59

## 6) Merge Cleaned SCB Data with DAIOE Weights

Join the cleaned SCB monthly panel with the DAIOE level-1 yearly metrics.

In [25]:
scb_months_lf =scb_lf_clean\
                .join(
                    weighted_daioe,
                    left_on=["code_1", "year"],
                    right_on=["ssyk_code", "year"],
                    how = "left"
                )\
                    .drop("level")
                    
scb_months_lf.limit(10).collect()

shape: (10, 62)
┌────────┬─────┬──────────┬───────┬───┬───────────────┬──────────────┬──────────────┬──────────────┐
│ code_1 ┆ sex ┆ month    ┆ value ┆ … ┆ pctl_daioe_ln ┆ pctl_daioe_t ┆ pctl_daioe_s ┆ pctl_daioe_g │
│ ---    ┆ --- ┆ ---      ┆ ---   ┆   ┆ gmod_wavg     ┆ ranslat_wavg ┆ peechrec_wav ┆ enai_wavg    │
│ str    ┆ str ┆ str      ┆ f64   ┆   ┆ ---           ┆ ---          ┆ g            ┆ ---          │
│        ┆     ┆          ┆       ┆   ┆ f64           ┆ f64          ┆ ---          ┆ f64          │
│        ┆     ┆          ┆       ┆   ┆               ┆              ┆ f64          ┆              │
╞════════╪═════╪══════════╪═══════╪═══╪═══════════════╪══════════════╪══════════════╪══════════════╡
│ 1      ┆ men ┆ 2015-Jan ┆ 169.8 ┆ … ┆ 75.0          ┆ 75.0         ┆ 75.0         ┆ 75.0         │
│ 1      ┆ men ┆ 2015-Feb ┆ 164.8 ┆ … ┆ 75.0          ┆ 75.0         ┆ 75.0         ┆ 75.0         │
│ 1      ┆ men ┆ 2015-Mar ┆ 156.2 ┆ … ┆ 75.0          ┆ 75.0         ┆ 75.0         ┆ 75.0         │
│ 1      ┆ men ┆ 2015-Apr ┆ 171.5 ┆ … ┆ 75.0          ┆ 75.0         ┆ 75.0         ┆ 75.0         │
│ 1      ┆ men ┆ 2015-May ┆ 177.8 ┆ … ┆ 75.0          ┆ 75.0         ┆ 75.0         ┆ 75.0         │
│ 1      ┆ men ┆ 2015-Jun ┆ 151.0 ┆ … ┆ 75.0          ┆ 75.0         ┆ 75.0         ┆ 75.0         │
│ 1      ┆ men ┆ 2015-Jul ┆ 174.6 ┆ … ┆ 75.0          ┆ 75.0         ┆ 75.0         ┆ 75.0         │
│ 1      ┆ men ┆ 2015-Aug ┆ 174.4 ┆ … ┆ 75.0          ┆ 75.0         ┆ 75.0         ┆ 75.0         │
│ 1      ┆ men ┆ 2015-Sep ┆ 157.0 ┆ … ┆ 75.0          ┆ 75.0         ┆ 75.0         ┆ 75.0         │
│ 1      ┆ men ┆ 2015-Oct ┆ 189.5 ┆ … ┆ 75.0          ┆ 75.0         ┆ 75.0         ┆ 75.0         │
└────────┴─────┴──────────┴───────┴───┴───────────────┴──────────────┴──────────────┴──────────────┘

In [26]:
inspect_lazy(scb_months_lf)

Rows: 2,394
Columns: 62

## 7) Export the Cleaned Monthly Output

Write the final cleaned and merged monthly dataset to parquet.

In [27]:
scb_months_lf.sink_parquet(data_dir / "scb_months_lvl1.parquet")